version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: stolen_device
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data/compose/:/var/lib/mysql
