version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: stolen_device
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data/stack/:/var/lib/mysql

  app:
    build: .
    command: bundle exec rackup -p 8080
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - RACK_ENV=container
      - MYSQL_MAX_CONNECTIONS=25
      - MYSQL_URL=mysql2://root:${MYSQL_PASSWORD}@mysql/stolen_device
      - LOG_LEVEL=info
